import type { GameSpec } from "../types/gameSpec";

export const SEED_GAMES: GameSpec[] = [
  {
    id: "lava-leap",
    title: "Lava Leap",
    author: "seed",
    bg: "#18211F",
    gravity: 1000,
    jumpVelocity: -460,
    input: "tap_jump",
    bodies: [
      {
        id: "hero",
        kind: "player",
        shape: "rect",
        x: 8,
        y: 76,
        w: 7,
        h: 8,
        color: "#D8FF46",
      },
      {
        id: "start-platform",
        kind: "platform",
        shape: "rect",
        x: 0,
        y: 85,
        w: 26,
        h: 6,
        color: "#8A5B3D",
      },
      {
        id: "step-one",
        kind: "platform",
        shape: "rect",
        x: 4,
        y: 71,
        w: 28,
        h: 2,
        color: "#9C6B45",
      },
      {
        id: "step-two",
        kind: "platform",
        shape: "rect",
        x: 8,
        y: 57,
        w: 28,
        h: 2,
        color: "#A9764D",
      },
      {
        id: "summit",
        kind: "platform",
        shape: "rect",
        x: 12,
        y: 43,
        w: 30,
        h: 2,
        color: "#B78355",
      },
      {
        id: "lava",
        kind: "hazard",
        shape: "rect",
        x: 0,
        y: 92,
        w: 100,
        h: 8,
        color: "#FF5A36",
      },
      {
        id: "flag",
        kind: "goal",
        shape: "rect",
        x: 10,
        y: 28,
        w: 5,
        h: 12,
        color: "#6BE675",
      },
    ],
    win: { type: "reach_goal" },
    lose: [{ type: "touch_hazard" }, { type: "fall_off" }],
  },
];
