import type { GameSpec } from "../types/gameSpec";

export const SEED_GAMES: GameSpec[] = [
  {
    id: "lava-leap",
    title: "Lava Leap",
    author: "seed",
    bg: "#1A1423",
    gravity: 1000,
    jumpVelocity: -460,
    input: "tap_jump",
    bodies: [
      {
        id: "hero",
        kind: "player",
        shape: "rect",
        x: 8,
        y: 76,
        w: 7,
        h: 8,
        color: "#FACC15",
        emoji: "😀",
      },
      {
        id: "start-platform",
        kind: "platform",
        shape: "rect",
        x: 0,
        y: 85,
        w: 26,
        h: 6,
        color: "#94A3B8",
      },
      {
        id: "step-one",
        kind: "platform",
        shape: "rect",
        x: 4,
        y: 71,
        w: 28,
        h: 2,
        color: "#94A3B8",
      },
      {
        id: "step-two",
        kind: "platform",
        shape: "rect",
        x: 8,
        y: 57,
        w: 28,
        h: 2,
        color: "#94A3B8",
      },
      {
        id: "summit",
        kind: "platform",
        shape: "rect",
        x: 12,
        y: 43,
        w: 30,
        h: 2,
        color: "#94A3B8",
      },
      {
        id: "lava",
        kind: "hazard",
        shape: "rect",
        x: 0,
        y: 92,
        w: 100,
        h: 8,
        color: "#FF4D3D",
        emoji: "🔥",
      },
      {
        id: "flag",
        kind: "goal",
        shape: "rect",
        x: 10,
        y: 28,
        w: 5,
        h: 12,
        color: "#4ADE80",
        emoji: "🚩",
      },
    ],
    win: { type: "reach_goal" },
    lose: [{ type: "touch_hazard" }, { type: "fall_off" }],
  },
  {
    id: "spike-rain",
    title: "Spike Rain",
    author: "seed",
    bg: "#12071F",
    gravity: 0,
    jumpVelocity: -400,
    input: "drag_x",
    bodies: [
      {
        id: "paddle",
        kind: "player",
        shape: "rect",
        x: 39,
        y: 82,
        w: 22,
        h: 5,
        color: "#22D3EE",
        immovable: true,
        emoji: "🛹",
      },
      {
        id: "spike-a",
        kind: "hazard",
        shape: "circle",
        x: 13,
        y: 8,
        w: 6,
        h: 6,
        color: "#FB7185",
        vy: 110,
        emoji: "💀",
      },
      {
        id: "spike-b",
        kind: "hazard",
        shape: "circle",
        x: 72,
        y: 22,
        w: 7,
        h: 7,
        color: "#FB7185",
        vy: 85,
        emoji: "💀",
      },
      {
        id: "spike-c",
        kind: "hazard",
        shape: "circle",
        x: 39,
        y: 39,
        w: 5,
        h: 5,
        color: "#FB7185",
        vy: 135,
        emoji: "💀",
      },
      {
        id: "spike-d",
        kind: "hazard",
        shape: "circle",
        x: 90,
        y: 54,
        w: 6,
        h: 6,
        color: "#FB7185",
        vy: 100,
        emoji: "💀",
      },
    ],
    win: { type: "survive_ms", ms: 10000 },
    lose: [{ type: "touch_hazard" }],
  },
  {
    id: "moon-bounce",
    title: "Moon Bounce",
    author: "seed",
    bg: "#0F1B33",
    gravity: 220,
    jumpVelocity: -420,
    input: "tap_jump",
    bodies: [
      {
        id: "moon-runner",
        kind: "player",
        shape: "circle",
        x: 50,
        y: 80,
        w: 8,
        h: 8,
        color: "#E0F2FE",
        bounce: 0.85,
        emoji: "🌙",
      },
      {
        id: "moon-floor",
        kind: "platform",
        shape: "rect",
        x: 18,
        y: 88,
        w: 64,
        h: 5,
        color: "#94A3B8",
      },
      {
        id: "moon-spikes-left",
        kind: "hazard",
        shape: "rect",
        x: 0,
        y: 91,
        w: 16,
        h: 9,
        color: "#A78BFA",
        emoji: "🌵",
      },
      {
        id: "moon-spikes-right",
        kind: "hazard",
        shape: "rect",
        x: 84,
        y: 91,
        w: 16,
        h: 9,
        color: "#A78BFA",
        emoji: "🌵",
      },
      {
        id: "moon-star-one",
        kind: "collectible",
        shape: "circle",
        x: 50,
        y: 62,
        w: 5,
        h: 5,
        color: "#FDE047",
        emoji: "⭐",
      },
      {
        id: "moon-star-two",
        kind: "collectible",
        shape: "circle",
        x: 50,
        y: 46,
        w: 5,
        h: 5,
        color: "#FDE047",
        emoji: "⭐",
      },
      {
        id: "moon-star-three",
        kind: "collectible",
        shape: "circle",
        x: 50,
        y: 30,
        w: 5,
        h: 5,
        color: "#FDE047",
        emoji: "⭐",
      },
    ],
    win: { type: "collect_all" },
    lose: [{ type: "touch_hazard" }],
  },
  {
    id: "star-dash",
    title: "Star Dash",
    author: "seed",
    bg: "#2A0E3F",
    gravity: 900,
    jumpVelocity: -420,
    input: "drag_x",
    bodies: [
      {
        id: "dash-orb",
        kind: "player",
        shape: "circle",
        x: 15,
        y: 84,
        w: 6,
        h: 6,
        color: "#67E8F9",
        immovable: true,
        emoji: "🛸",
      },
      {
        id: "dash-floor",
        kind: "platform",
        shape: "rect",
        x: 0,
        y: 90,
        w: 100,
        h: 5,
        color: "#64748B",
      },
      {
        id: "dash-star-one",
        kind: "collectible",
        shape: "circle",
        x: 32,
        y: 85,
        w: 5,
        h: 5,
        color: "#FDE047",
        emoji: "🪙",
      },
      {
        id: "dash-star-two",
        kind: "collectible",
        shape: "circle",
        x: 55,
        y: 85,
        w: 5,
        h: 5,
        color: "#FDE047",
        emoji: "🪙",
      },
      {
        id: "dash-star-three",
        kind: "collectible",
        shape: "circle",
        x: 78,
        y: 85,
        w: 5,
        h: 5,
        color: "#FDE047",
        emoji: "🪙",
      },
      {
        id: "dash-comet",
        kind: "hazard",
        shape: "circle",
        x: 48,
        y: 72,
        w: 8,
        h: 8,
        color: "#F472B6",
        vx: 80,
        emoji: "☄️",
      },
    ],
    win: { type: "collect_all" },
    lose: [{ type: "touch_hazard" }, { type: "fall_off" }],
  },
  {
    id: "thrust-escape",
    title: "Thrust Escape",
    author: "seed",
    bg: "#030712",
    gravity: 500,
    jumpVelocity: -460,
    input: "hold_thrust",
    bodies: [
      {
        id: "thrust-ship",
        kind: "player",
        shape: "circle",
        x: 50,
        y: 50,
        w: 8,
        h: 8,
        color: "#F97316",
        emoji: "🚀",
      },
      {
        id: "thrust-lava",
        kind: "hazard",
        shape: "rect",
        x: 0,
        y: 92,
        w: 100,
        h: 8,
        color: "#EF4444",
        emoji: "🔥",
      },
    ],
    win: { type: "survive_ms", ms: 8000 },
    lose: [{ type: "touch_hazard" }],
  },
];
